#!/bin/bash

if ! grep -s -q "name='DeviceBackend'" setup.py
then
  echo You are not in the top of package directory
  exit 1
fi

mkdir ./debian
cp ./debian_src/* ./debian

search_pattern="^\([0-9]\+.[0-9]\+.[0-9]\+\)-\([0-9]\+\)-g\(.*\)"
version=`git describe --tag --long | sed -n "s/$search_pattern/\1/p"`
tag_offset=`git describe --tag --long | sed -n "s/$search_pattern/\2/p"`
git_hash=`git describe --tag --long | sed -n "s/$search_pattern/\3/p"`
date_time=`date -R`

echo version=$version
echo tag_offset=$tag_offset
echo git_hash=$git_hash
echo date_time=$date_time
echo

if [ $tag_offset -eq 0 ]
then
  if git status | grep -q "Changes to be committed:"
    then
      echo This is DEV version
      pkg_version="$version-1"
      commit="not_committed ($git_hash)"
    else
      echo This is PROD release
      pkg_version=$version
      commit=$git_hash
  fi
else
  if git status | grep -q "Changes to be committed:"
    then
      echo This is DEV version
      offset=$(( $tag_offset + 1 ))
      pkg_version="$version-$offset"
      commit="not_committed ($git_hash)"
    else
      echo This is DEV version
      pkg_version="$version-$tag_offset"
      commit=$git_hash
  fi
fi

sed -i "s/__version__/$pkg_version/g" ./debian/changelog
sed -i "s/__commit__/$commit/g" ./debian/changelog
sed -i "s/__date__/$date_time/g" ./debian/changelog

sed -i "s/__commit__/$commit/g" ./debian/control
